// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDL79sEsAUq1aodHJhvNmmLBIHjb9nsaJI',
    appId: '1:418449219919:android:ca49b26d96409320f8253a',
    messagingSenderId: '418449219919',
    projectId: 'dw-vendor',
    storageBucket: 'dw-vendor.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMCm3CsuDTqL03s6GLbF6LLzh-gRjevBc',
    appId: '1:418449219919:ios:d8a9d08e8e9683f7f8253a',
    messagingSenderId: '418449219919',
    projectId: 'dw-vendor',
    storageBucket: 'dw-vendor.appspot.com',
    iosBundleId: 'com.dukanwalaa.vendor.vendor',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcHDFAk-6qJSm_vbjswpUxSU2N-8HnqtI',
    appId: '1:418449219919:web:1ac635643c247cbdf8253a',
    messagingSenderId: '418449219919',
    projectId: 'dw-vendor',
    authDomain: 'dw-vendor.firebaseapp.com',
    storageBucket: 'dw-vendor.appspot.com',
    measurementId: 'G-XEERWBTJYQ',
  );

}